# coding: utf-8

"""
    LLM-REPL Pipeline API

    An API for generating, evaluating, and refactoring Python code using Large Language Models (LLMs) and a Python REPL.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: qte@77
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.evaluate_body import EvaluateBody  # noqa: E501
from swagger_client.rest import ApiException


class TestEvaluateBody(unittest.TestCase):
    """EvaluateBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEvaluateBody(self):
        """Test EvaluateBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.evaluate_body.EvaluateBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
